### ISSUE TITLE
identify "I'm a have-not" surveys in Pew

### ISSUE THREAD

**Issue by fsolt** [fsolt/class_consciousness#1]
identify the surveys, confirm that we have them already for "haves/have-nots", and identify the variable name for the "I'm a have-not" question

**Comment by fsolt** [comment]
Sorry gang, I just realized I'd already done this.

**Comment by dongericoyu** [comment]
I am just looking at the surveys. Do you still want us to look for the question in surveys of the other years, or we should prepare for another assignment, such as cleaning up the data?

**Comment by fsolt** [comment]
The data were already cleaned along with the "haves/have-nots" question, so there's really nothing else to do, data-wise.
