### ISSUE TITLE
Formatting check

### ISSUE THREAD

**Issue by sammo3182** [fsolt/class_consciousness#10]
Here is a formatting checklist, which should be gone through before the submission yet after every other issue is fixed.

1.    All citations in the text are listed in the bibliography.
2.    All grammatical errors and typos are corrected, and every line is double spaced, including the references.
3.    The title of the paper is relatively short and to the point.
4.    The paper length is no longer than agreed upon in the decision letter.
5.    You have provided a short title of the article suitable for the running header.  This short title should be no longer than 50 characters.
6.    The paper includes (a) a title page with full title, name, and contact information for every author, and (b) a separate abstract page.
7.    You have provided 4-5 keywords under the abstract.
8.    At the bottom of the abstract page, if necessary, you have indicated that (a) supplementary materials will be available in an online appendix and (b) any data and materials necessary to replicate analyses in the published paper are available on Dataverse.  Two sentences should be sufficient to convey this information. "Thank yous" should be in a separate Acknowledgments section. (Additional details about these various things are below.)
9.    Required file formats are Word or LaTex; if you are sending a LaTex file, be sure to include any related files (a bibliography, for example) as well as a PDF file created from your final version and checked carefully to ensure that special characters and math are displayed correctly.
10. The length should be less than 10 pages.

**Comment by jsong10** [comment]
@fsolt Did you provide 4-5 keywords when you submitted the paper? In case you did not, I propose the following keywords. Please share your thoughts on this.

economic inequality, class consciousness, replication crisis, reproducibility

**Comment by fsolt** [comment]
I concur—those are good choices.

**Comment by jsong10** [comment]
@fsolt For the formatting check, I have tried to compile PDF for our finalized version, but R-studio is continuously reporting errors. Do you experience the same problem?

**Comment by fsolt** [comment]
There seems to be a `checkpoint` issue, ironically enough.  I'm making progress with it, and will keep you posted.

**Comment by fsolt** [comment]
Okay fixed.  Be sure to delete all cache files, restart R, update all relevant packages, and it'll run (at least that's what did the trick for me).

**Comment by fsolt** [comment]
Point 2 is a real problem---our references are single spaced.  Maybe we'll try to slip that by.

**Comment by jsong10** [comment]
If we do not have any problems regarding generating a PDF file, I think we can upload our replication files to the Dataverse. @dongericoyu @sammo3182 @kwhudson, did all of you succeed in generating the PDF?

**Comment by fsolt** [comment]
I'm working on assembling the minimum set of replication files.  I'll keep you posted.

**Comment by fsolt** [comment]
All done.

**Comment by fsolt** [comment]
For real!  Just finished submitting!  (Jeez, that took 2 hours?!?)
