### ISSUE TITLE
Data and Replication

### ISSUE THREAD

**Issue by sammo3182** [fsolt/class_consciousness#11]
* Authors of quantitative papers must submit their data and all associated replication files to the JOP's Dataverse: https://dataverse.harvard.edu/dataverse/jop. 

* A recommended data/replication statement, at the bottom of the abstract page below the supplemental-materials statement, would be: "Replication files are available in the JOP Data Archive on Dataverse (http://thedata.harvard.edu/dvn/dv/jop)."

**Comment by jsong10** [comment]
@fsolt Do you want me to upload a ZIP archive for our replication files, as you did for our meritocracy paper? Or, will you handle this part?

**Comment by fsolt** [comment]
Done. http://dx.doi.org/10.7910/DVN/UCCJIB
