### ISSUE TITLE
Biographical statement

### ISSUE THREAD

**Issue by sammo3182** [fsolt/class_consciousness#12]
Please write a brief biographical statement for each author. These statements should take the following form: NAME is a/an/the POSITION at INSTITUTION, CITY, STATE ZIP CODE. Please use abbreviations for the states instead of writing each one out ("AZ" instead of "Arizona," for example). Please insert this information into your manuscript immediately following your References section.

**Comment by kwhudson** [comment]
Done. Thanks Hu.
