### ISSUE TITLE
Reproducible Statement of NJL

### ISSUE THREAD

**Issue by sammo3182** [fsolt/class_consciousness#16]
"I was surprised on p.3 which states that NJL could not reproduce their own results. Indeed, NJL's readme file states, "Further, we have not been able to exactly replicate the estimates reported in Table 3." However, I think the text as currently written is misleading because NJL were able to replicate their Table 2, which is the key point of emphasis on p.3. I think the wording should be revised to clarify this point."

Reframe the language in the second paragraph of page 3---e.g., casting footnote 3 to a shorter version and put it into the content.

**Comment by fsolt** [comment]
This critique is off the mark.  Neither the original code provided by NJL (in v2.1 of the replication materials and earlier) nor the new version they posted in v3.0 reproduces the published results exactly.  This is readily seen in the coef for median hh income: .107 in AJPS; .111 when replicated from either version of the replication materials.

<img width="404" alt="screen shot 2016-11-20 at nov 20 1 49 43 pm" src="https://cloud.githubusercontent.com/assets/6536645/20465666/3f25ce8a-af28-11e6-9f65-a8772bb1964a.png">

<img width="722" alt="screen shot 2016-11-20 at nov 20 1 50 32 pm" src="https://cloud.githubusercontent.com/assets/6536645/20465667/5ff1fd3c-af28-11e6-8c75-f55079a2d877.png">
<img width="716" alt="screen shot 2016-11-20 at nov 20 1 50 44 pm" src="https://cloud.githubusercontent.com/assets/6536645/20465668/6011232e-af28-11e6-9941-29001f550eb0.png">

**Comment by fsolt** [comment]
Despite the differences in the replication scripts (v2.1 uses xtlogit, v3.0 uses xtmelogit), it appears they give the same results--results that don't match the publication.

**Comment by fsolt** [comment]
Well, fine: I guess "The NJL reproducibility materials note that the article’s authors are themselves unable to reproduce these results exactly (Newman, Johnston, and Lown 2016)" isn't right.  So minor revision necessary--even if they didn't note it, they can't do it.

**Comment by kwhudson** [comment]
I was just looking into this. Thanks for running the models with the newest replication materials.

Essentially then we just need to drop the bit about the authors acknowledging that they can't reproduce the results and provide a bit more explanation in the memo?

**Comment by fsolt** [comment]
I think either "The article’s authors are themselves unable to reproduce these results exactly (see Newman, Johnston, and Lown 2016)" or "The NJL reproducibility materials do not themselves reproduce these results exactly (see Newman, Johnston, and Lown 2016)" will do the trick.
