### ISSUE TITLE
Transition Sentence in p.6

### ISSUE THREAD

**Issue by sammo3182** [fsolt/class_consciousness#17]
"The middle of p.6 addresses a second aspect of the NJL paper. I think this should be clarified. Perhaps starting the paragraph with, 'Another important question that NJL ask is….'"

Adding a transition sentence to the second paragraph in p.6.

**Comment by kwhudson** [comment]
I'll alter the wording here slightly. I think a transition already exists, but it could be stated more clearly that the paper is shifting focus.
