### ISSUE TITLE
get Pew data programmatically

### ISSUE THREAD

**Issue by fsolt** [fsolt/class_consciousness#2]
will need to get a package to do so written first.

**Comment by fsolt** [comment]
see https://github.com/fsolt/pewdata

**Comment by sammo3182** [comment]
1. We may need a link for "acs0509-counties.csv"
2. I got an error for runing pew_download (.Rfile has been set up):
   Error:   Summary: UnknownError
    Detail: An unknown server-side error occurred while processing the command.
    class: org.openqa.selenium.WebDriverException 
3. It turns out when I refer the working directory with "../" in Win 10, it doesn't work. But when I use "./", problem was solved.

**Comment by fsolt** [comment]
1. I added the file to the repo.  It would be nice to have the download coded, though.
2. Good luck with that one!  Let me know when you figure it out.  Wait--do you have Firefox installed?  pew_download depends on it.  Guess I should add that to the comment re .Rprofile.
3. Were you running the whole script or just one chunk?  The relevant working directory--and so the relative path to other files--changes.  Try Dean Attali's ezknitr package (it's on CRAN).  I haven't worked with it, but it is meant to deal with this problem.

**Comment by fsolt** [comment]
Another alternative is the rprojroot package.  Anyway, I'll let you choose and implement a solution if you like.  Or just change the code when you want to run the chunk only and change it back to run the whole file, which is what I did.  Fortunately, it's a pretty simple chunk that I really only needed to run by itself once to confirm that it worked.

**Comment by sammo3182** [comment]
For item 2, I installed the Firefox, but it is not enough to run `Rselenium`. For windows users, I need to manually add the system path of firefox. Even with that setting, the package does not work for my Win 10 at least. The data were smoothly downloaded, but at the unzipping process, it returned error: 
`In dir.create(download_dir) :
  cannot create dir '..\data\pew\haves_havenots', reason 'No such file or directory'`
When I manually created the folders according to the directory, R returns an error claiming, "permission denial".

Btw, I found that `Rselenium` actually can run with chrome or other browsers, and tried to apply your `pewdata` based on chrome. Rstudio successfully called the browser out, while there seems a problem relating to VPS  impeding downloading. 

For item 3, I am running that chunk by chunk now. So, I guess you are right.

**Comment by fsolt** [comment]
Hmm.  If you try the example in the `pew_download` help file `pew_download(file_id = c(20059299, 20058139))`, does it work?  If so, then the issue is with the file system (i.e., point 3).  If not, we'll need to further debug `pewdata` on Win 10.

**Comment by sammo3182** [comment]
It doesn't work. The data were successfully downloaded, though. Here's the message:
![image](https://cloud.githubusercontent.com/assets/6463211/15364873/b5f76cf8-1ce3-11e6-8bf3-6b582c80546f.png)

**Comment by fsolt** [comment]
hmm.  try `pew_download(file_id = c(20059299, 20058139), delete_zip = FALSE)` ?

**Comment by sammo3182** [comment]
The function created the folder "pew_data" in the working directory, and didn't return any error, BUT when the function finished running, the folder was still empty. It seemed that the function downloaded the data somewhere, but I can't see where they were saved.

**Comment by fsolt** [comment]
Curiouser and curiouser.  Thanks for trying that.

**Comment by fsolt** [comment]
I updated `pewdata` yesterday, and there's a chance the new CRAN version solves this problem, Hu.  Give it a try?
